<?php

namespace Saippuakauppias\SafeBrowsing\Type;

class ThreatType
{
    const THREAT_TYPE_UNSPECIFIED = 'THREAT_TYPE_UNSPECIFIED';
    const MALWARE = 'MALWARE';
    const SOCIAL_ENGINEERING = 'SOCIAL_ENGINEERING';
    const UNWANTED_SOFTWARE = 'UNWANTED_SOFTWARE';
    const POTENTIALLY_HARMFUL_APPLICATION = 'POTENTIALLY_HARMFUL_APPLICATION';
}
